"""Download + convert Reverie's built-in mood music into apps/readest-app/public/music/.

  python3 tools/mood-music/install.py

The tracks are CC-BY 4.0 (Scott Buckley, Kevin MacLeod) but too big for git, like the model.
Also regenerates src/mood/builtInMusic.ts and public/music/CREDITS.md from PICKS below.
Needs curl and ffmpeg (libmp3lame).
"""
import glob
import os
import re
import shutil
import subprocess
import tempfile
import urllib.parse
from concurrent.futures import ThreadPoolExecutor

APP = os.path.join(os.path.dirname(__file__), '../../apps/readest-app')
PUB = os.path.join(APP, 'public/music')

SB = 'https://www.scottbuckley.com.au/library/wp-content/uploads/'
SOURCE = {
    'Scott Buckley': 'https://www.scottbuckley.com.au/library/',
    'Kevin MacLeod': 'https://incompetech.com/music/royalty-free/music.html',
}
sb = lambda title, path: (title, 'Scott Buckley', SB + path)
km = lambda title: (
    title,
    'Kevin MacLeod',
    'https://incompetech.com/music/royalty-free/mp3-royaltyfree/' + urllib.parse.quote(title) + '.mp3',
)

# Picked in Phase 5: 4 per mood.
PICKS = {
    'Joy': [sb('Born of the Sky', '2025/08/BornOfTheSky.mp3'), km('Carefree'), km('Wholesome'), km('Life of Riley')],
    'Excitement': [sb('Honour Among Thieves', '2025/04/HonourAmongThieves.mp3'), km('Volatile Reaction'), km('Movement Proposition'), km('Exhilarate')],
    'Anticipation': [sb('Starfire', '2026/01/Starfire.mp3'), km('Hiding Your Reality'), km('Eternal Hope'), km('Frost Waltz')],
    'Wonder/Awe': [sb('Aphelion', '2026/04/Aphelion.mp3'), km('Crossing the Chasm'), km('Enchanted Journey'), km('Magic Forest')],
    'Mystery': [sb('Incredulity', '2025/04/Incredulity.mp3'), sb('Origami', '2025/10/Origami.mp3'), km('Investigations'), km('Myst on the Moor')],
    'Romance': [sb('Amberlight', '2025/03/Amberlight.mp3'), km('Touching Moments Two - Higher'), km('Heartwarming'), km('Gymnopedie No 1')],
    'Tenderness': [sb('With These Hands', '2026/06/WithTheseHands.mp3'), sb('Echoes of Home', '2025/05/EchoesOfHome.mp3'), km('Meditation Impromptu 01'), km('Gymnopedie No 2')],
    'Peace/Calm': [sb('Home Was You', '2026/07/HomeWasYou.mp3'), km('Meditation Impromptu 02'), km('Meditation Impromptu 03'), km('Dreamer')],
    'Neutral': [sb('Wildflowers', '2025/12/Wildflowers.mp3'), sb('Phoenix (2026)', '2026/03/Phoenix2026.mp3'), km('Long Stroll'), km('Wallpaper')],
    'Sadness': [sb('In This Moment', '2026/08/InThisMoment.mp3'), sb('Convergence', '2026/04/Convergence.mp3'), km('Sad Trio'), km('Heartbreaking')],
    'Grief/Despair': [sb('Unraveling', '2026/05/Unraveling.mp3'), sb('Memories of Stone', '2026/02/MemoriesOfStone.mp3'), sb('Penumbra', '2025/07/Penumbra.mp3'), km('Despair and Triumph')],
    'Fear': [sb('Eyes in the Void', '2025/06/EyesInTheVoid.mp3'), km('Ossuary 1 - A Beginning'), km('Echoes of Time'), km('Darkling')],
    'Tension/Suspense': [km('Oppressive Gloom'), km('Covert Affair'), km('Anxiety'), km('Interloper')],
    'Anger': [sb('Song of the Forge', '2025/11/SongOfTheForge.mp3'), sb('Simulacra', '2025/03/Simulacra.mp3'), km('Chase Pulse'), km('Five Armies')],
    'Disgust': [km('Ossuary 6 - Air'), km('Gloom Horizon'), km('The Hive'), km('Unholy Knight')],
}

slug = lambda text: re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')
plan = [(mood, title, artist, url, f'{slug(title)}.mp3') for mood, tracks in PICKS.items() for title, artist, url in tracks]


def install(item):
    mood, title, artist, url, file = item
    out_dir = os.path.join(PUB, slug(mood))
    os.makedirs(out_dir, exist_ok=True)
    with tempfile.NamedTemporaryFile(suffix='.mp3') as src:
        if subprocess.run(['curl', '-sfL', '--retry', '5', '--max-time', '900', '-o', src.name, url]).returncode:
            return f'download failed: {mood} / {title}'
        # ~130 kbps VBR MP3: plays everywhere (incl. Safari/WebKit), much smaller than the 256-320 kbps originals.
        r = subprocess.run(
            ['ffmpeg', '-v', 'error', '-y', '-i', src.name, '-map', '0:a', '-codec:a', 'libmp3lame', '-q:a', '5',
             '-metadata', f'title={title}', '-metadata', f'artist={artist}', '-metadata', 'copyright=CC-BY 4.0',
             os.path.join(out_dir, file)],
            capture_output=True, text=True)
        return f'convert failed: {mood} / {title}: {r.stderr[:200]}' if r.returncode else None


for d in glob.glob(os.path.join(PUB, '*/')):
    shutil.rmtree(d)
with ThreadPoolExecutor(4) as pool:
    errors = [e for e in pool.map(install, plan) if e]
if errors:
    raise SystemExit('\n'.join(errors))

ts = [
    '// Built-in mood tracks shipped with Reverie. Files: public/music/<mood>/<file>.',
    '// All CC-BY 4.0: credit in public/music/CREDITS.md. Generated by tools/mood-music/install.py.',
    "import type { Mood } from './moods';",
    '',
    'export interface BuiltInTrack {',
    '  file: string;',
    '  title: string;',
    "  artist: 'Scott Buckley' | 'Kevin MacLeod';",
    '}',
    '',
    'export const BUILT_IN_MUSIC: Record<Mood, BuiltInTrack[]> = {',
]
md = ['# Reverie built-in music', '', 'All tracks are licensed under Creative Commons Attribution 4.0 (CC-BY 4.0):',
      'https://creativecommons.org/licenses/by/4.0/', '',
      f"- Scott Buckley: {SOURCE['Scott Buckley']}", f"- Kevin MacLeod (incompetech.com): {SOURCE['Kevin MacLeod']}", '']
for mood in PICKS:
    ts.append(f"  {mood if re.fullmatch(r'\w+', mood) else repr(mood)}: [")
    md += [f'## {mood}', '']
    for m, title, artist, _, file in plan:
        if m != mood:
            continue
        ts.append(f"    {{ file: '{file}', title: {repr(title)}, artist: '{artist}' }},")
        md.append(f'- `{slug(mood)}/{file}`: "{title}" by {artist}, CC-BY 4.0, {SOURCE[artist]}')
    ts.append('  ],')
    md.append('')
ts += ['};', '']
open(os.path.join(APP, 'src/mood/builtInMusic.ts'), 'w').write('\n'.join(ts))
open(os.path.join(PUB, 'CREDITS.md'), 'w').write('\n'.join(md))
print(f'installed {len(plan)} tracks')
