// Built-in mood tracks shipped with Reverie. Files: public/music/<mood>/<file>.
// All CC-BY 4.0: credit in public/music/CREDITS.md. Generated by tools/mood-music/install.py.
import type { Mood } from './moods';

export interface BuiltInTrack {
  file: string;
  title: string;
  artist: 'Scott Buckley' | 'Kevin MacLeod';
}

export const BUILT_IN_MUSIC: Record<Mood, BuiltInTrack[]> = {
  Joy: [
    { file: 'born-of-the-sky.mp3', title: 'Born of the Sky', artist: 'Scott Buckley' },
    { file: 'carefree.mp3', title: 'Carefree', artist: 'Kevin MacLeod' },
    { file: 'wholesome.mp3', title: 'Wholesome', artist: 'Kevin MacLeod' },
    { file: 'life-of-riley.mp3', title: 'Life of Riley', artist: 'Kevin MacLeod' },
  ],
  Excitement: [
    { file: 'honour-among-thieves.mp3', title: 'Honour Among Thieves', artist: 'Scott Buckley' },
    { file: 'volatile-reaction.mp3', title: 'Volatile Reaction', artist: 'Kevin MacLeod' },
    { file: 'movement-proposition.mp3', title: 'Movement Proposition', artist: 'Kevin MacLeod' },
    { file: 'exhilarate.mp3', title: 'Exhilarate', artist: 'Kevin MacLeod' },
  ],
  Anticipation: [
    { file: 'starfire.mp3', title: 'Starfire', artist: 'Scott Buckley' },
    { file: 'hiding-your-reality.mp3', title: 'Hiding Your Reality', artist: 'Kevin MacLeod' },
    { file: 'eternal-hope.mp3', title: 'Eternal Hope', artist: 'Kevin MacLeod' },
    { file: 'frost-waltz.mp3', title: 'Frost Waltz', artist: 'Kevin MacLeod' },
  ],
  'Wonder/Awe': [
    { file: 'aphelion.mp3', title: 'Aphelion', artist: 'Scott Buckley' },
    { file: 'crossing-the-chasm.mp3', title: 'Crossing the Chasm', artist: 'Kevin MacLeod' },
    { file: 'enchanted-journey.mp3', title: 'Enchanted Journey', artist: 'Kevin MacLeod' },
    { file: 'magic-forest.mp3', title: 'Magic Forest', artist: 'Kevin MacLeod' },
  ],
  Mystery: [
    { file: 'incredulity.mp3', title: 'Incredulity', artist: 'Scott Buckley' },
    { file: 'origami.mp3', title: 'Origami', artist: 'Scott Buckley' },
    { file: 'investigations.mp3', title: 'Investigations', artist: 'Kevin MacLeod' },
    { file: 'myst-on-the-moor.mp3', title: 'Myst on the Moor', artist: 'Kevin MacLeod' },
  ],
  Romance: [
    { file: 'amberlight.mp3', title: 'Amberlight', artist: 'Scott Buckley' },
    {
      file: 'touching-moments-two-higher.mp3',
      title: 'Touching Moments Two - Higher',
      artist: 'Kevin MacLeod',
    },
    { file: 'heartwarming.mp3', title: 'Heartwarming', artist: 'Kevin MacLeod' },
    { file: 'gymnopedie-no-1.mp3', title: 'Gymnopedie No 1', artist: 'Kevin MacLeod' },
  ],
  Tenderness: [
    { file: 'with-these-hands.mp3', title: 'With These Hands', artist: 'Scott Buckley' },
    { file: 'echoes-of-home.mp3', title: 'Echoes of Home', artist: 'Scott Buckley' },
    {
      file: 'meditation-impromptu-01.mp3',
      title: 'Meditation Impromptu 01',
      artist: 'Kevin MacLeod',
    },
    { file: 'gymnopedie-no-2.mp3', title: 'Gymnopedie No 2', artist: 'Kevin MacLeod' },
  ],
  'Peace/Calm': [
    { file: 'home-was-you.mp3', title: 'Home Was You', artist: 'Scott Buckley' },
    {
      file: 'meditation-impromptu-02.mp3',
      title: 'Meditation Impromptu 02',
      artist: 'Kevin MacLeod',
    },
    {
      file: 'meditation-impromptu-03.mp3',
      title: 'Meditation Impromptu 03',
      artist: 'Kevin MacLeod',
    },
    { file: 'dreamer.mp3', title: 'Dreamer', artist: 'Kevin MacLeod' },
  ],
  Neutral: [
    { file: 'wildflowers.mp3', title: 'Wildflowers', artist: 'Scott Buckley' },
    { file: 'phoenix-2026.mp3', title: 'Phoenix (2026)', artist: 'Scott Buckley' },
    { file: 'long-stroll.mp3', title: 'Long Stroll', artist: 'Kevin MacLeod' },
    { file: 'wallpaper.mp3', title: 'Wallpaper', artist: 'Kevin MacLeod' },
  ],
  Sadness: [
    { file: 'in-this-moment.mp3', title: 'In This Moment', artist: 'Scott Buckley' },
    { file: 'convergence.mp3', title: 'Convergence', artist: 'Scott Buckley' },
    { file: 'sad-trio.mp3', title: 'Sad Trio', artist: 'Kevin MacLeod' },
    { file: 'heartbreaking.mp3', title: 'Heartbreaking', artist: 'Kevin MacLeod' },
  ],
  'Grief/Despair': [
    { file: 'unraveling.mp3', title: 'Unraveling', artist: 'Scott Buckley' },
    { file: 'memories-of-stone.mp3', title: 'Memories of Stone', artist: 'Scott Buckley' },
    { file: 'penumbra.mp3', title: 'Penumbra', artist: 'Scott Buckley' },
    { file: 'despair-and-triumph.mp3', title: 'Despair and Triumph', artist: 'Kevin MacLeod' },
  ],
  Fear: [
    { file: 'eyes-in-the-void.mp3', title: 'Eyes in the Void', artist: 'Scott Buckley' },
    {
      file: 'ossuary-1-a-beginning.mp3',
      title: 'Ossuary 1 - A Beginning',
      artist: 'Kevin MacLeod',
    },
    { file: 'echoes-of-time.mp3', title: 'Echoes of Time', artist: 'Kevin MacLeod' },
    { file: 'darkling.mp3', title: 'Darkling', artist: 'Kevin MacLeod' },
  ],
  'Tension/Suspense': [
    { file: 'oppressive-gloom.mp3', title: 'Oppressive Gloom', artist: 'Kevin MacLeod' },
    { file: 'covert-affair.mp3', title: 'Covert Affair', artist: 'Kevin MacLeod' },
    { file: 'anxiety.mp3', title: 'Anxiety', artist: 'Kevin MacLeod' },
    { file: 'interloper.mp3', title: 'Interloper', artist: 'Kevin MacLeod' },
  ],
  Anger: [
    { file: 'song-of-the-forge.mp3', title: 'Song of the Forge', artist: 'Scott Buckley' },
    { file: 'simulacra.mp3', title: 'Simulacra', artist: 'Scott Buckley' },
    { file: 'chase-pulse.mp3', title: 'Chase Pulse', artist: 'Kevin MacLeod' },
    { file: 'five-armies.mp3', title: 'Five Armies', artist: 'Kevin MacLeod' },
  ],
  Disgust: [
    { file: 'ossuary-6-air.mp3', title: 'Ossuary 6 - Air', artist: 'Kevin MacLeod' },
    { file: 'gloom-horizon.mp3', title: 'Gloom Horizon', artist: 'Kevin MacLeod' },
    { file: 'the-hive.mp3', title: 'The Hive', artist: 'Kevin MacLeod' },
    { file: 'unholy-knight.mp3', title: 'Unholy Knight', artist: 'Kevin MacLeod' },
  ],
};
